Refuse_classification/Refuse_classification/urls.py
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
import re
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^article/', include('apps.article.urls', namespace='article')),
    url(r'^search/', include('apps.search.urls', namespace='search')),
    url(r'^reviews/', include('apps.reviews.urls', namespace='reviews')),
    url(r'^apis/', include('apps.apis.urls', namespace="apis")),
    # url(r'^base/$', include('apps.urls', namespace='base')),
    url(r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')), serve,
        {"document_root": settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
    url(r'^deliver$',TemplateView.as_view(template_name='deliver.html'),name='deliver')
]

handler404 = views.my404

Refuse_classification/apps/accounts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

# CBV => class base view
# FBV => function base view

urlpatterns = [
    # 注册
    url(r'register/$', views.Register.as_view(), name="register"),
    # 登录
    url(r'^login/$', views.Login.as_view(), name='login'),
    # 退出
    url(r'logout/$', views.logout, name="logout"),
    # 忘记密码
    url(r'password/forget/$', views.PasswordForget.as_view(), name="password_forget"),
    # 重置密码
    url(r'password/reset/(\w+)/$', views.PasswordReset.as_view(), name="password_reset"),
]

Refuse_classification/apps/apis/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^mobile_captcha/$', views.get_mobile_captcha, name="mobile_captcha"),
    url(r'^get_captcha/$', views.get_captcha, name='get_captcha'),
    url(r'^check_captcha/$', views.check_captcha, name='check_captcha'),
    url(r'^change_avator/$', views.ChangeAvator.as_view(), name='change_avator'),
    url(r'^change_passwd/$',views.ChangePasswdView.as_view(),name='change_passwd')
]

Refuse_classification/apps/article/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', views.index, name='index'),
    url(r'^news/(?P<id>\d+)/$', views.news, name='news'),
    url(r'^interest/(?P<id>\d+)/$', views.interest, name='interest'),
    url(r'^base/$', views.Base.as_view(), name='base'),
    url(r'^contents/(?P<id>\d+)/$', views.contents, name='contents'),
    url(r'^interest_con/(?P<id>\d+)/$', views.interest_con, name='interest_con'),

]

Refuse_classification/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    username = models.CharField(verbose_name="用户名", max_length=18,unique=True)
    password = models.CharField(verbose_name="密码", max_length=128)
    mobile = models.CharField(max_length=11, verbose_name="手机号")
    qq = models.CharField(max_length=11, verbose_name="QQ号")
    avator_sor = models.ImageField(upload_to="avator/%Y%m%d/", default="avator/default.png", verbose_name="头像")

    class Meta:
        verbose_name = '用户类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class FindPassword(models.Model):
    verify_code = models.CharField(max_length=128, verbose_name="验证码")
    email = models.EmailField(verbose_name="邮箱")
    creat_time = models.DateTimeField(auto_now=True, verbose_name="重置时间")
    status = models.BooleanField(default=False, verbose_name="是否已重置")

Refuse_classification/apps/accounts/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import check_password as auth_check_password
from .models import User


# 用户注册
class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(label="确认密码", widget=widgets.PasswordInput(attrs={"class":"input", "placeholder": "请再输入密码","id":"pass2"}))
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(attrs={"class":"input", "placeholder":"验证码", "error_messages": {"invalid": "验证码错误"},"id":"mobile_cap"}))
    class Meta:
        model = User
        fields = ['username', 'mobile', 'password']
        widgets = {
            'username': widgets.TextInput(attrs={"class": "input", "placeholder": "请输入用户名","id":"user1"}),
            'mobile': widgets.TextInput(attrs={"class":"input", "placeholder": "请输入手机号","id":"id_mobile"}),
            'password': widgets.PasswordInput(attrs={"class": "input", "placeholder": "请输入密码","id":"pass1"}),
        }

    # username是否重复django会自动检查，因为它是unique的，所以不需要自己写clean_username
    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")

    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")


# 用户登录表单
# 因为是登录功能，所以不适合ModelForm。
# ModelForm对于unique字段会检查是否已经存在，如果存在，is_valid结果会为False
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length="24",
                               widget=widgets.TextInput(attrs={"class": "input", "placeholder": "用户名","id":"user"}))
    captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"class": "input", "placeholder": "验证码", "onblur": "check_captcha()",
               "error_messages": {"invalid": "验证码错误"},"id":"catcha"}))
    password = forms.CharField(label="密 码",
                               widget=widgets.PasswordInput(attrs={"class": "input", "placeholder": "请输入密码","id":"pass"}))

    def check_password(self):
        print('check password')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = User.objects.get(username=username)
            if user:
                return user, auth_check_password(password, user.password)
            else:
                raise ValidationError("用户名或密码不正确")
        except:
            return None, False

    def clean_username(self):
        print(self.cleaned_data.get("username"))
        ret = User.objects.filter(username=self.cleaned_data.get("username"))
        if ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户不存在")

Refuse_classification/apps/accounts/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse, render_to_response
from django.views.generic import View
from django.core.cache import cache
from django.contrib.auth.hashers import make_password
from django.contrib import auth
from django.http import JsonResponse
import logging
from .forms import RegisterForm, LoginForm
from .models import User,FindPassword
logger = logging.getLogger("account")

# Create your views here.
def test(request):
    return HttpResponse("帐户视图")


class Register(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "register.html", {"form":form})

    # Ajax提交表单
    def post(self, request):
        ret = {"status": 400, "msg": "调用方式错误"}
        # 检查是不是ajax的请求
        if request.is_ajax():
            form = RegisterForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data["username"]
                password = form.cleaned_data["password"]
                mobile = form.cleaned_data["mobile"]
                mobile_captcha = form.cleaned_data["mobile_captcha"]
                mobile_captcha_reids = cache.get(mobile)
                if mobile_captcha == mobile_captcha_reids:
                    user = User.objects.create(username=username, password=make_password(password))
                    user.save()
                    ret['status'] = 200
                    ret['msg'] = "注册成功"
                    logger.debug(f"新用户{user}注册成功！")
                    user = auth.authenticate(username=username, password=password)
                    if user is not None and user.is_active:
                        auth.login(request, user)
                        logger.debug(f"新用户{user}登录成功")
                    else:
                        logger.error(f"新用户{user}登录失败")
                else:
                    # 验证码错误
                    ret['status'] = 401
                    ret['msg'] = "验证码错误或过期"
            else:
                ret['status'] = 402
                ret['msg'] = form.errors
        logger.debug(f"用户注册结果：{ret}")
        return JsonResponse(ret)

"""
HttpResonse
JsonResponse
render => 执行context_processors=> messages, request
render_to_response => 不会执行context_processors
"""
class Login(View):
    def get(self, request):
        # 设置下一跳转地址(如果get有next，如果没有跳转到repo:index)
        request.session["next"] = request.GET.get('next', reverse('article:index'))
        # 如果已登录，则直接跳转到index页面
        # request.user 表示的是当前登录的用户对象,没有登录 `匿名用户`
        if request.user.is_authenticated:
            return redirect(request.session["next"])
        form = LoginForm()
        return render(request, "login.html", {"form":form})
        # return render_to_response("login.html", {"form":form})


    # Form表单直接提交
    def post(self, request):
        ret={"code":400,"msg":"调用方式错误"}
        if request.is_ajax():
            # 表单数据绑定
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data["username"]
                captcha = form.cleaned_data["captcha"]
                session_captcha_code = request.session.get("captcha_code", "")
                logger.debug(f"登录提交验证码:{captcha}-{session_captcha_code}")
                # 验证码一致
                print(captcha.lower(), session_captcha_code.lower())
                if captcha.lower() == session_captcha_code.lower():
                    user, flag = form.check_password()
                    # user = auth.authenticate(username=username, password=password)
                    if flag and user and user.is_active:
                        auth.login(request, user)
                        logger.info(f"{user.username}登录成功")
                        ret["code"] = 200
                        ret["msg"] = "登录成功"
                        # 跳转到next
                        return JsonResponse(ret)
                    ret["code"] = 402
                    ret["msg"] = "用户名或密码错误"
                    logger.error(f"{username}登录失败, 用户名或密码错误")
                else:
                    ret["code"] = 401
                    ret["msg"] = "验证码错误"
                    logger.error(f"{username}登录失败, 验证码错误")
            else:
                ret["msg"] = form.errors
                logger.error(ret["msg"])
        return JsonResponse(ret)


def logout(request):
    auth.logout(request)
    return redirect(reverse("article:index"))

import random
import string
from django.core.mail import send_mail

class PasswordForget(View):
    def post(self, request):
        email = request.POST.get("email")
        if email and User.objects.filter(email=email):
            verify_code = "".join(random.choices(string.ascii_lowercase + string.digits, k=128))
            url = f"{request.scheme}://{request.META['HTTP_HOST']}/accounts/password/reset/{verify_code}?email={email}"
            ret = FindPassword.objects.get_or_create(email=email)
            # (<FindPassword: FindPassword object>, True)
            ret[0].verify_code = verify_code
            ret[0].status = False
            ret[0].save()
            send_mail('注册用户验证信息', url, None, [email])
            msg = {'code': 200, 'msg': "邮件发送成功，请登录邮箱查看！"}
            return JsonResponse(msg)
        else:
            msg = {'code': 404, 'msg': "输入的邮箱不存在！"}
            return JsonResponse(msg)

class PasswordReset(View):
    def get(self, request, verify_code):
        import datetime
        create_time_newer = datetime.datetime.utcnow()-datetime.timedelta(minutes=30)
        email = request.GET.get("email")
        # 邮箱、verify_code、status=False、时间近30分钟
        find_password = FindPassword.objects.filter(status=False, verify_code=verify_code, email=email, creat_time__gte=create_time_newer)
        # great_then_equal, lte, lt, gt
        if verify_code and find_password:
            return render(request, "password_reset.html")
        else:
            return HttpResponse("链接失效或有误")

    def post(self, request, verify_code):
        import datetime
        create_time_newer = datetime.datetime.utcnow() - datetime.timedelta(minutes=30)
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        if len(password1.strip()) == 0:
            msg = "密码为空，重置失败"
        elif password2 == password1:
            try:
                find_password = FindPassword.objects.get(status=False, verify_code=verify_code, creat_time__gte=create_time_newer)
                user = User.objects.get(email=find_password.email)
                user.set_password(password1)
                user.save()
                msg = "重置密码成功，请登录"
                find_password.status = True
                find_password.save()
            except Exception as ex:
                # 记日志 ex
                msg = "出错啦"

        else:
            msg = "两次密码不一致，重置失败"
        return render(request, "password_reset.html", {"msg":msg})

Refuse_classification/apps/accounts/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户登录</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'assets/js/jquery.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
          <form class="form-signin" method="post">
            {% csrf_token %}
            <h2 class="form-signin-heading">登录</h2>
            <div class="login-wrap">
{#                {{ request.user }}#}
{#                {{ DEFAULT_MESSAGE_LEVELS }}#}
                {{ form.username}}
                {{ form.password}}
                {{ form.captcha}}
                <a href="javascript:void(0);"><img id="captcha_img" src="#" ></a>
                <div class="user-reg">
                    <a href="{% url 'accounts:register' %}"> 用户注册</a>
                    <span class="pull-right"> <a href=""> 忘记密码?</a></span>
                </div>
                <button class="btn btn-lg btn-login btn-block" type="submit">登录</button>
                <p class="msg"></p>
            </div>
          </form>
        </div>
    <script>
    get_captcha_img();
    $("#captcha_img").click(get_captcha_img);

    function get_captcha_img() {
        $.ajax({
            url: '{% url 'apis:get_captcha' %}',
            type: 'GET',
            dataType: 'text',
            success: function (data) {
                $('#captcha_img').attr('src', data);
            }
        });
    }

        // 这里在form中定义了，如果没定义可以用jquery添加事件
    // $("#id_captcha").blur(check_captcha);

    // 当失去焦点时检查验证码
    function check_captcha() {
        var captcha_code = $('#id_captcha').val();
        if (captcha_code.length == 0){
            return false
        }
        $.ajax({
            url: '{% url 'apis:check_captcha' %}',
            type: 'GET',
            dataType: 'json',
            data: {"captcha_code": captcha_code},
            success: function (data) {
                if(data.code == 400){
                     $('.msg').html("验证码错误");
                }else{
                    $('.msg').html("");
                }
            }
        });
    };
    </script>
    </body>
</html>

Refuse_classification/apps/accounts/templates/password_reset.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block lunbo %}
{% endblock %}
{% block css %}
    <style>
        input{height: 50px;width: 300px;}
    </style>
{% endblock %}
{% block content %}
    <div class="login-form container" style="margin-left: 18%">
    <form class="sign-in-htm" id="login_form" method="post">
        <div class="group col-xs-9">
            <label for="password1" class="label">新的密码</label>
            <input type="password" placeholder="请输入新的密码" name="password1" class="input">
        </div>
        <div class="group col-xs-9">
            <label for="password2" class="label">确认密码</label>
            <input type="password" placeholder="请再次输入密码" name="password2" class="input">
        </div>
        <div class="group col-xs-9" style="margin-top: 35px">
            <button type="submit" class="button">提交</button>
        </div>
        <div class="group col-xs-9" style="text-align: center"><h2>{{ msg }}</h2></div>
    </form>
    </div>




{% endblock %}

Refuse_classification/apps/accounts/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户注册-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'assets/js/jquery.js' %}"></script>
    {# 加载提示工具对应的js和css #}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/gritter/css/jquery.gritter.css' %}" />
    <script type="text/javascript" src="{% static 'assets/gritter/js/jquery.gritter.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
            <form class="form-signin" id="register_form">
              {% csrf_token %}
              <h2 class="form-signin-heading">用户注册</h2>
              <div class="login-wrap">
                  {{ form.username }}
                  {{ form.password }}
                  {{ form.password2 }}
                  {{ form.mobile }}
                  {{ form.mobile_captcha }}
                  {# 给发送短信按钮添加动作 #}
                  <input onclick="sendmessage(this,60);" type="button" value="发送短信"  class="btn btn-info" style="height:38px;width: 125px;"/>
                  <button class="btn btn-lg btn-login btn-block" type="button" id="register_btn">注册</button>
                  <label class="checkbox">
                      <span class="pull-right"> 已有帐号， <a href="{% url 'accounts:login' %}"> 请登录 </a></span>
                  </label>
                  <div class="alert alert-block alert-danger fade in">
                        <button data-dismiss="alert" class="close close-sm" type="button">
                            <i class="icon-remove"></i>
                        </button>
                        <strong>提醒!</strong> 错误提示信息~~
                  </div>
              </div>
            </form>
        </div>
    {# 添加js动作#}
    <script>
        {# 发送短信验证码 #}
        function sendmessage(obj,second){
            var telRegex = /(13|14|15|17|18)\d{9}/;
            if(telRegex.test($.trim($("#id_mobile").val()))){
                $.ajax({
                    url: "{% url 'apis:mobile_captcha' %}",
                    type: "GET",
                    dataType: "json",
                    data: {"mobile": $("#id_mobile").val()},
                    success: function (data) {
                         $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '提交结果',
                            // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                            text: data.msg
                        });
                    }
                });
                countDown(obj,second)
            } else{
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: '提交结果',
                    // (string | mandatory) the text inside the notification
                    //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                    text: '手机号有误'
                });
            }
        }

        {# 重新发送倒计时 #}
        function countDown(obj,second){
        // 如果秒数还是大于0，则表示倒计时还没结束
         if(second>=0){
              // 获取默认按钮上的文字
              if(typeof buttonDefaultValue === 'undefined' ){
                buttonDefaultValue =  obj.defaultValue;
            }
            // 按钮置为不可点击状态
            obj.disabled = true;
            // 按钮里的内容呈现倒计时状态
            obj.value = buttonDefaultValue+'('+second+')';
            // 时间减一
            second--;
            // 一秒后重复执行
            setTimeout(function(){countDown(obj,second);},1000);
            // 否则，按钮重置为初始状态
            }else{
            // 按钮置未可点击状态
            obj.disabled = false;
            // 按钮里的内容恢复初始状态
            obj.value = buttonDefaultValue;
           }
        }
    $("#register_btn").click(function () {
          // some_check
          $.ajax({
              url: "{% url 'accounts:register' %}",
              type: "POST",
              dataType: "json",
              data: $("#register_form").serialize(), // {"username":'cali'}
              success: function (data) {
                  if(data.status == 200 ){
                      window.location.href='{% url 'article:index' %}';
                  }else{
                      msg = "新错误类型";
                      if(data.status == 400 || data.status == 401){
                          msg = data.msg
                      }else{
                          // 402 => form.errors
                          for(var i in data.msg){
                              msg = i+data.msg[i];
                              break
                          }
                      }
                       $.gritter.add({
                          // (string | mandatory) the heading of the notification
                          title: '提交结果',
                          // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                          text: msg
                      });
                   }
              },
              // 解决csrftoken
              beforeSend: function(xhr, settings) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
              }
          });
      });
    </script>

    </body>
</html>